// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brrkapvwhaupesbxboxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJycmthcHZ3aGF1cGVzYnhib3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NTg3MjcsImV4cCI6MjA1MzMzNDcyN30.TkDs-8Yk2loej7q9Y0w9DDfAh7ciXEuJuQcV0sJ6wTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);