
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brrkapvwhaupesbxboxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJycmthcHZ3aGF1cGVzYnhib3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NTg3MjcsImV4cCI6MjA1MzMzNDcyN30.TkDs-8Yk2loej7q9Y0w9DDfAh7ciXEuJuQcV0sJ6wTY";

if (!SUPABASE_URL) throw new Error('Missing SUPABASE_URL');
if (!SUPABASE_PUBLISHABLE_KEY) throw new Error('Missing SUPABASE_PUBLISHABLE_KEY');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a simple connection test function
export const testConnection = async () => {
  try {
    const { data, error } = await supabase.from('profiles').select('count').limit(1);
    if (error) throw error;
    console.log('Supabase connection test successful:', { data });
    return true;
  } catch (error) {
    console.error('Supabase connection test failed:', error);
    return false;
  }
};
